"""Cross-framework parity tests against frozen fixtures.

Fixtures are generated by ``scripts/generate_parity_fixtures.py`` using the
pure-CPU torch oracle (``scripts/torch_ref_cpu.py``). The fixture matrix
and the tolerance policy live in this file — update both together when
adjusting the parity contract.
"""

from __future__ import annotations

from pathlib import Path

import mlx.core as mx
import numpy as np
import pytest

import flash_kda_mlx
from _helpers import (
    DEFAULT_ATOL,
    DEFAULT_RTOL,
    FIXTURES_DIR,
    assert_allclose_mlx,
    fixture_to_mlx_inputs,
    load_fixture,
)


FIXED_BASIC_CASES = []
FIXED_STATE_CASES = []
VARLEN_CASES = []


def _scan_fixtures() -> None:
    """Populate case lists at import time so pytest can parametrize over them."""
    if not FIXTURES_DIR.exists():
        return
    for path in sorted(FIXTURES_DIR.glob("*.npz")):
        name = path.stem
        if name.startswith("fixed__") and "no_state" in name:
            FIXED_BASIC_CASES.append(name)
        elif name.startswith("fixed__"):
            FIXED_STATE_CASES.append(name)
        elif name.startswith("varlen__"):
            VARLEN_CASES.append(name)


_scan_fixtures()


def _require_fixtures():
    if not (FIXED_BASIC_CASES or FIXED_STATE_CASES or VARLEN_CASES):
        pytest.skip(
            "No fixtures found. Run:\n"
            "  uv run --no-config python scripts/generate_parity_fixtures.py"
        )


# ---------------------------------------------------------------------------
# Parity tests
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("case", FIXED_BASIC_CASES or ["__no_fixtures__"])
def test_parity_fixed_no_state(case):
    if case == "__no_fixtures__":
        pytest.skip("No fixtures; run scripts/generate_parity_fixtures.py")
    fx = load_fixture(case)
    kwargs = fixture_to_mlx_inputs(fx)
    out = mx.zeros(fx["out_expected"].shape, dtype=mx.float32)

    result, _ = flash_kda_mlx.fwd(
        out=out,
        final_state=None,
        **kwargs,
    )
    assert_allclose_mlx(
        result, fx["out_expected"],
        rtol=DEFAULT_RTOL, atol=DEFAULT_ATOL,
        err_msg=f"output mismatch for {case}",
    )


@pytest.mark.parametrize("case", FIXED_STATE_CASES or ["__no_fixtures__"])
def test_parity_fixed_with_state(case):
    if case == "__no_fixtures__":
        pytest.skip("No fixtures; run scripts/generate_parity_fixtures.py")
    fx = load_fixture(case)
    kwargs = fixture_to_mlx_inputs(fx)

    # Presence of final_state_expected determines whether the call requested
    # a final state. Match dtype to the initial_state if present, else fp32.
    want_final = "final_state_expected" in fx
    if want_final:
        state_dtype = mx.float32 if "state_fp32" in fx and int(fx["state_fp32"]) == 1 else mx.bfloat16
        final_placeholder = mx.zeros(fx["final_state_expected"].shape, dtype=state_dtype)
    else:
        final_placeholder = None

    out = mx.zeros(fx["out_expected"].shape, dtype=mx.float32)
    result, final = flash_kda_mlx.fwd(
        out=out, final_state=final_placeholder, **kwargs,
    )

    assert_allclose_mlx(
        result, fx["out_expected"],
        rtol=DEFAULT_RTOL, atol=DEFAULT_ATOL,
        err_msg=f"output mismatch for {case}",
    )
    if want_final:
        assert final is not None
        assert_allclose_mlx(
            final, fx["final_state_expected"],
            rtol=DEFAULT_RTOL, atol=DEFAULT_ATOL,
            err_msg=f"final_state mismatch for {case}",
        )


@pytest.mark.parametrize("case", VARLEN_CASES or ["__no_fixtures__"])
def test_parity_varlen(case):
    if case == "__no_fixtures__":
        pytest.skip("No fixtures; run scripts/generate_parity_fixtures.py")
    fx = load_fixture(case)
    kwargs = fixture_to_mlx_inputs(fx)

    want_final = "final_state_expected" in fx
    if want_final:
        state_dtype = mx.float32 if "state_fp32" in fx and int(fx["state_fp32"]) == 1 else mx.bfloat16
        final_placeholder = mx.zeros(fx["final_state_expected"].shape, dtype=state_dtype)
    else:
        final_placeholder = None

    out = mx.zeros(fx["out_expected"].shape, dtype=mx.float32)
    result, final = flash_kda_mlx.fwd(
        out=out, final_state=final_placeholder, **kwargs,
    )
    assert_allclose_mlx(
        result, fx["out_expected"],
        rtol=DEFAULT_RTOL, atol=DEFAULT_ATOL,
        err_msg=f"output mismatch for {case}",
    )
    if want_final:
        assert_allclose_mlx(
            final, fx["final_state_expected"],
            rtol=DEFAULT_RTOL, atol=DEFAULT_ATOL,
            err_msg=f"final_state mismatch for {case}",
        )
